apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: myingress
spec:
  rules:
  - host: wisdompetmed.com
    http:
      paths:
      - backend:
          service:
            name: myservice
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
