apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypvpod
  name: mypvpod
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: myvolume
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: mypvc
status: {}
